<?php

namespace App\Trait;

trait CarsTrait
{
    public function getAllBrands(): array
    {
        return [
            'ABARTH', 'AIWAYS', 'ALEKO', 'ALFA ROMEO', 'ALPINE RENAULT', 'ARO', 'ASIA', 'ASTON MARTIN', 'AUDI', 'AUSTIN',
            'AUTOBIANCHI', 'AUVERLAND', 'BEDFORD', 'BEE BEE AUTOMOTIVE', 'BENTLEY', 'BERTONE', 'BMW', 'BUICK', 'BYD',
            'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'CITROEN', 'COURB', 'CUPRA', 'DACIA', 'DAEWOO', 'DAF', 'DAIHATSU', 'DAIMLER',
            'DATSUN', 'DODGE', 'DS', 'EBRO', 'FERRARI', 'FEST', 'FIAT', 'FISKER', 'FORD', 'FSO-POLSKI', 'GAC GONOW', 'GME',
            'GRANDIN', 'HONDA', 'HYUNDAI', 'INEOS', 'INFINITI', 'INNOCENTI', 'ISUZU', 'IVECO', 'JAGUAR', 'JEEP', 'KIA', 'LADA',
            'LANCIA', 'LAND ROVER', 'LDV', 'LEAPMOTOR', 'LEXUS', 'LOTUS', 'LYNK&CO', 'MAHINDRA', 'MAN', 'MARUTI', 'MASERATI',
            'MATRA', 'MAZDA', 'MCC', 'MEGA', 'MERCEDES', 'MG', 'MIA', 'MINI', 'MITSUBISHI', 'MPM MOTORS', 'NISSAN', 'OPEL',
            'PANHARD', 'PEUGEOT', 'PIAGGIO', 'PONTIAC', 'PORSCHE', 'PROTON', 'RENAULT', 'ROVER', 'SAAB', 'SANTANA', 'SEAT',
            'SERES DFSK', 'SKODA', 'SMART', 'SSANGYONG', 'SUBARU', 'SUNBEAM', 'SUZUKI', 'TALBOT', 'TATA', 'TESLA', 'THINK',
            'TOYOTA', 'TRIUMPH', 'UMM', 'VINFAST', 'VOLKSWAGEN', 'VOLVO', 'ZASTAVA', 'ZAZ',
        ];
    }

    public function getAllModels(): array
    {
        return [
            ['brand' => 'ABARTH', 'model' => ['124 Spider', '595', '695']],
            ['brand' => 'AIWAYS', 'model' => ['U5']],
            ['brand' => 'ALFA ROMEO', 'model' => ['4C', 'Giulia', 'Stelvio', 'Giulietta', 'MiTo']],
            ['brand' => 'ALPINE RENAULT', 'model' => ['A110']],
            ['brand' => 'ARO', 'model' => ['10', '24', '240', '244', '245', 'Spartana', 'Scamp', 'IMS', 'Rhino', 'Super-Spartana']],
            ['brand' => 'ASIA', 'model' => ['AM-825', 'Rocsta']],
            ['brand' => 'ASTON MARTIN', 'model' => ['DB9', 'DB11', 'DBS', 'Rapide', 'Vantage', 'Virage']],
            ['brand' => 'AUDI', 'model' => ['100', '200', '80', '90', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'RSQ3', 'RSQ8', 'S1', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SQ2', 'SQ5', 'SQ7', 'SQ8', 'TT']],
            ['brand' => 'AUSTIN', 'model' => ['1100', '1300', '1800', 'A35', 'A40', 'A60', 'Allegro', 'Ambassador', 'America', 'Cambridge', 'Maestro', 'Maxi', 'Metro', 'Mini', 'Montego', 'Princess', 'Sheerline', 'Taxi', 'Westminster', '16 HP', '18 HP', '20 HP', '3-Litre', '4-Litre', '8 HP', 'A30', 'A40 Somerset', 'Ambassador (1906)']],
            ['brand' => 'AUTOBIANCHI', 'model' => ['Bianchina', 'Eden Roc', 'Primula', 'Y10']],
            ['brand' => 'AUVERLAND', 'model' => ['A3', 'A3B', 'A4', 'A5', 'D3', 'D4']],
            ['brand' => 'BEDFORD', 'model' => ['CA', 'CF', 'J', 'KD', 'M', 'OB', 'RL', 'SB', 'TK']],
            ['brand' => 'BEE BEE AUTOMOTIVE', 'model' => ['CB']],
            ['brand' => 'BENTLEY', 'model' => ['Arnage', 'Azure', 'Bentayga', 'Brooklands', 'Continental', 'Eight', 'Mulsanne', 'S1', 'S2', 'S3', 'T-Series', 'Turbo R']],
            ['brand' => 'BERTONE', 'model' => ['Freeclimber']],
            ['brand' => 'BMW', 'model' => ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z1', 'Z3', 'Z4', 'i3', 'i8', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'X3 M', 'X4 M', 'X5 M', 'X6 M']],
            ['brand' => 'BUICK', 'model' => ['Century', 'Electra', 'Enclave', 'Encore', 'Estate', 'Excelle', 'GL6', 'GL8', 'LaCrosse', 'LeSabre', 'Lucerne', 'Park Avenue', 'Rainier', 'Reatta', 'Regal', 'Rendezvous', 'Riviera', 'Roadmaster', 'Skyhawk', 'Skylark', 'Somerset', 'Special', 'Terraza', 'Verano']],
            ['brand' => 'BYD', 'model' => ['F0', 'F3', 'F5', 'F6', 'F8', 'F3DM', 'F6DM', 'E6', 'G6', 'L3', 'M6', 'Qin', 'S6', 'Tang']],
            ['brand' => 'CADILLAC', 'model' => ['ATS', 'BLS', 'CT4', 'CT5', 'CT6', 'CTS', 'Catera', 'DTS', 'DeVille', 'ELR', 'Escalade', 'Seville', 'SRX', 'STS', 'XT4', 'XT5', 'XT6', 'XTS']],
            ['brand' => 'CHEVROLET', 'model' => ['Alero', 'Astro', 'Avalanche', 'Aveo', 'Bel Air', 'Beretta', 'Blazer', 'Bolt', 'Camaro', 'Caprice', 'Captiva', 'Cavalier', 'Celebrity', 'Chevelle', 'Citation', 'City Express', 'Cobalt', 'Colorado', 'Corsica', 'Corvair', 'Corvette', 'Cruze', 'El Camino', 'Equinox', 'Express', 'GMC Vam', 'HHR', 'Impala', 'Lacetti', 'Lumina', 'Malibu', 'Metro', 'Monte Carlo', 'Monza', 'Nova', 'Orlando', 'Prizm', 'S-10', 'Sonic', 'Spark', 'Suburban', 'Tahoe', 'Tavera', 'Trailblazer']],
            ['brand' => 'CITROEN', 'model' => ['2CV', 'AMI', 'AX', 'Acadiane', 'BX', 'C-Crosser', 'C-Elysee', 'C-Metisse', 'C-Triomphe', 'C1', 'C2', 'C3', 'C3 Aircross', 'C3-XR', 'C4', 'C4 Aircross', 'C4 Cactus', 'C4 Picasso', 'C5', 'C6', 'C8', 'Cactus', 'Celysée', 'Cleo', 'Diana', 'DS3', 'DS4', 'DS5', 'DS6', 'DS7', 'DS9', 'Evasion', 'Grand C4 Picasso', 'Grand C4 Spacetourer', 'GS', 'ID', 'Jumpy', 'LN', 'M35', 'M45', 'Méhari', 'Nemo', 'Saxo', 'SM', 'SpaceTourer', 'Traction Avant', 'Xantia', 'XM', 'Xsara', 'Xsara Picasso', 'ZX']],
            ['brand' => 'COURB', 'model' => ['C14', 'C26']],
            ['brand' => 'CUPRA', 'model' => ['Ateca', 'Formentor', 'Leon']],
            ['brand' => 'DACIA', 'model' => ['1300', '1310', '1410', 'Duster', 'Lodgy', 'Logan', 'Sandero']],
            ['brand' => 'DAEWOO', 'model' => ['Espero', 'Evanda', 'Korando', 'Lacetti', 'Lanos', 'Leganza', 'Matiz', 'Nexia', 'Nubira', 'Prince', 'Tico']],
            ['brand' => 'DAF', 'model' => ['33', '44', '46', '55', '66', '600', '750', 'A-Type', 'DO', 'FA', 'FT', 'LF', 'MB', 'TB']],
            ['brand' => 'DAIHATSU', 'model' => ['Applause', 'Charade', 'Copen', 'Cuore', 'Feroza', 'Materia', 'Mira', 'Move', 'Rocky', 'Sirion', 'Terios', 'Trevis', 'YRV']],
            ['brand' => 'DAIMLER', 'model' => ['2.5 V8', '250', '250 V8', '420', '420 Sovereign', 'Double-Six', 'DS420', 'Majestic', 'Majestic Major', 'Sovereign', 'Super V8', 'XJ']],
            ['brand' => 'DATSUN', 'model' => ['240Z', '260Z', '280ZX', '300ZX', '310', '410', '411', '510', '520', '521', '620', '720', 'Bluebird', 'Cherry', 'F10', 'P510', 'Pickup', 'S130', 'S30', 'Sunny', 'Truck', 'Violet']],
            ['brand' => 'DODGE', 'model' => ['400', '600', 'Avenger', 'Caliber', 'Caravan', 'Challenger', 'Charger', 'Colt', 'Coronet', 'D-Series', 'Dakota', 'Dart', 'Daytona', 'Durango', 'Dynasty', 'Grand Caravan', 'Intrepid', 'Journey', 'Magnum', 'Monaco', 'Neon', 'Nitro', 'Polara', 'Ram', 'Shadow', 'Spirit', 'Stealth', 'Stratus', 'Viper']],
            ['brand' => 'DS', 'model' => ['3', '4', '5', '7']],
            ['brand' => 'EBRO', 'model' => ['E-350']],
            ['brand' => 'FERRARI', 'model' => ['208', '308', '328', '348', '360', '365', '400', '412', '430', '456', '458', '488', '512', '550', '575', '599', '612', '812', 'California', 'Dino', 'Enzo', 'F12', 'F355', 'F40', 'F430', 'F50', 'F8', 'FF', 'GTC4', 'LaFerrari', 'Mondial', 'Portofino', 'SF90', 'Testarossa', 'TR']],
            ['brand' => 'FEST', 'model' => ['Monica']],
            ['brand' => 'FIAT', 'model' => ['1100', '124', '125', '126', '127', '128', '130', '131', '132', '133', '500', '500L', '500X', '508', '600', '850', 'Albea', 'Argenta', 'Barchetta', 'Bravo', 'Cinquecento', 'Coupe', 'Croma', 'Dino', 'Doblo', 'Ducato', 'Fiorino', 'Freemont', 'Grande Punto', 'Idea', 'Linea', 'Marea', 'Multipla', 'Palio', 'Panda', 'Punto', 'Qubo', 'Regata', 'Ritmo', 'Scudo', 'Sedici', 'Seicento', 'Siena', 'Stilo', 'Strada', 'Tempra', 'Tipo', 'Ulysse', 'Uno', 'X1/9']],
            ['brand' => 'FISKER', 'model' => ['Karma']],
            ['brand' => 'FORD', 'model' => ['Aerostar', 'Aspire', 'Bronco', 'C-Max', 'Contour', 'Crown Victoria', 'E-Series', 'EcoSport', 'Edge', 'Escape', 'Escort', 'Excursion', 'Expedition', 'Explorer', 'F-150', 'F-250', 'F-350', 'Fairlane', 'Falcon', 'Fiesta', 'Five Hundred', 'Flex', 'Focus', 'Freestar', 'Freestyle', 'Fusion', 'Galaxy', 'Granada', 'GT', 'LTD', 'Maverick', 'Model A', 'Model T', 'Mondeo', 'Mustang', 'Probe', 'Ranchero', 'Ranger', 'Taurus', 'Tempo', 'Thunderbird', 'Transit', 'Windstar']],
            ['brand' => 'FSO-POLSKI', 'model' => ['125p', '1500', 'Polonez']],
            ['brand' => 'GAC GONOW', 'model' => ['GA200', 'GA200S', 'GA491', 'GA491S', 'GS50', 'GS50-II']],
            ['brand' => 'GME', 'model' => ['Ampera', 'Astra', 'Calibra', 'Cascada', 'Combo', 'Corsa', 'Crossland X', 'Frontera', 'Grandland X', 'Insignia', 'Karl', 'Manta', 'Meriva', 'Mokka', 'Movano', 'Olympia', 'Omega', 'Senator', 'Signum', 'Sintra', 'Speedster', 'Tigra', 'Vectra', 'Vivaro', 'Zafira']],
            ['brand' => 'GRANDIN', 'model' => ['GS1']],
            ['brand' => 'HONDA', 'model' => ['Accord', 'Acty', 'Airwave', 'Amaze', 'Avancier', 'Ballade', 'Beat', 'Brio', 'Capa', 'City', 'Civic', 'Concerto', 'Crosstour', 'CR-V', 'CR-Z', 'CRX', 'Domani', 'Edix', 'Element', 'Elysion', 'EV Plus', 'FCX', 'Fit', 'Freed', 'Freed Spike', 'HR-V', 'Insight', 'Inspire', 'Integra', 'Jade', 'Jazz', 'Legend', 'Life', 'Logo', 'Mobilio', 'N360', 'N600', 'NSX', 'Odyssey', 'Orthia', 'Passport', 'Pilot', 'Prelude', 'Rafaga', 'Ridgeline', 'S-MX', 'S2000', 'S500', 'S600', 'S800', 'Saber']],
            ['brand' => 'HYUNDAI', 'model' => ['Accent', 'Atos', 'Azera', 'Centennial', 'Elantra', 'Entourage', 'Equus', 'Excel', 'Genesis', 'Getz', 'Grandeur', 'H-1', 'H100', 'i10', 'i20', 'i30', 'i40', 'Ioniq', 'ix20', 'ix35', 'ix55', 'Kona', 'Lantra', 'Marcia', 'Matrix', 'Mighty', 'Nexo', 'Pony', 'S-Coupe', 'Santa Fe', 'Scoupe', 'Sonata', 'Starex', 'Terracan', 'Tiburon', 'Trajet', 'Tucson', 'Veloster', 'Venue', 'Veracruz', 'Verna', 'XG']],
            ['brand' => 'INEOS', 'model' => ['Grenadier']],
            ['brand' => 'INFINITI', 'model' => ['EX', 'FX', 'G', 'JX', 'M', 'Q30', 'Q40', 'Q45', 'Q50', 'Q60', 'Q70', 'QX', 'QX30', 'QX4', 'QX50', 'QX56', 'QX60', 'QX70', 'QX80']],
            ['brand' => 'INNOCENTI', 'model' => ['Mini', 'Regent', 'Small']],
            ['brand' => 'ISUZU', 'model' => ['117 Coupe', 'Amigo', 'Ascender', 'Aska', 'Axiom', 'Bighorn', 'D-Max', 'Florian', 'Gemini', 'Hombre', 'Impulse', 'KB', 'MU', 'Piazza', 'Rodeo', 'Stylus', 'Trooper', 'VehiCROSS', 'WFR']],
            ['brand' => 'IVECO', 'model' => ['Daily', 'TurboDaily']],
            ['brand' => 'JAGUAR', 'model' => ['420', 'Daimler', 'E-Type', 'F-Pace', 'F-Type', 'Mark 1', 'Mark 2', 'Mark IX', 'Mark X', 'S-Type', 'SS', 'X-Type', 'XE', 'XF', 'XJ', 'XJ220', 'XJR', 'XJS', 'XK', 'XK8', 'XKR', 'XKSS', 'XJ220']],
            ['brand' => 'JEEP', 'model' => ['Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade', 'Wagoneer', 'Wrangler']],
            ['brand' => 'KIA', 'model' => ['Amanti', 'Avella', 'Bongo', 'Borrego', 'Cadenza', 'Carens', 'Carnival', 'Cee\'d', 'Cerato', 'Clarus', 'Forte', 'K2', 'K3', 'K4', 'K5', 'K7', 'K900', 'Magentis', 'Mohave', 'Niro', 'Opirus', 'Optima', 'Picanto', 'Pregio', 'Pride', 'ProCeed', 'Quoris', 'Ray', 'Retona', 'Rio', 'Sedona', 'Seltos', 'Sephia', 'Sorento', 'Soul', 'Spectra', 'Sportage', 'Stinger', 'Stonic', 'Telluride', 'Venga', 'XCeed']],
            ['brand' => 'LADA', 'model' => ['4x4', '110', '1200', '1200S', '1300', '1300S', '1500', '1500S', '1600', '1600S', '2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '2109', '2110', '2111', '2112', '2120', '2121', '2123', '1200 Combi', '1200S Combi', '1300 Combi', '1300S Combi', '1500 Combi', '1500S Combi', '1600 Combi', '1600S Combi', '2102 Combi', '2103 Combi', '2104 Combi', '2105 Combi', '2106 Combi', '2107 Combi', '2108 Combi', '2109 Combi', '2110 Combi', '2111 Combi', '2112 Combi', '2120 Combi', '2121 Combi', '2123 Combi', '1200 Pickup', '1200S Pickup', '1300 Pickup', '1300S Pickup', '1500 Pickup', '1500S Pickup', '1600 Pickup', '1600S Pickup', '2102 Pickup', '2103 Pickup', '2104 Pickup', '2105 Pickup', '2106 Pickup', '2107 Pickup', '2108 Pickup', '2109 Pickup', '2110 Pickup', '2111 Pickup', '2112 Pickup', '2120 Pickup', '2121 Pickup', '2123 Pickup']],
            ['brand' => 'LANCIA', 'model' => ['2000', 'Beta', 'Dedra', 'Delta', 'Flaminia', 'Flavia', 'Fulvia', 'Gamma', 'Hyena', 'Kappa', 'Lybra', 'Monte Carlo', 'Musa', 'Phedra', 'Prisma', 'Stratos', 'Thema', 'Thesis', 'Trevi', 'Voyager', 'Y', 'Y10', 'Ypsilon', 'Zagato']],
            ['brand' => 'LAND ROVER', 'model' => ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'LR2', 'LR3', 'LR4', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar']],
            ['brand' => 'LDV', 'model' => ['Convoy', 'Cub', 'Maxus', 'Pilot']],
            ['brand' => 'LEAPMOTOR', 'model' => ['C11']],
            ['brand' => 'LEXUS', 'model' => ['CT', 'ES', 'GS', 'GX', 'HS', 'IS', 'LC', 'LFA', 'LS', 'LX', 'NX', 'RC', 'RX', 'SC', 'UX']],
            ['brand' => 'LOTUS', 'model' => ['Elan', 'Elite', 'Esprit', 'Evija', 'Exige', 'Evora', 'Super 7', 'T127', 'T128', 'T130', 'T131', 'T132', 'T150', 'T150C', 'T25', 'T52', 'T56', 'T64', 'T72', 'T78', 'T80', 'T81', 'T86', 'T87', 'T92', 'T94', 'T95', 'T96', 'T97', 'T99', 'T100', 'T101', 'T102', 'T107', 'T108', 'T109', 'T110', 'T111', 'T112', 'T113', 'T114', 'T115', 'T116', 'T118', 'T119', 'T120', 'T121', 'T122', 'T123', 'T124', 'T125', 'T126', 'T128', 'T129', 'T130', 'T131', 'T132', 'T134', 'T137', 'T138', 'T140', 'T141', 'T142', 'T143', 'T145', 'T146', 'T147', 'T148', 'T150', 'T151', 'T152', 'T153', 'T154', 'T155', 'T156', 'T157', 'T158', 'T159', 'T160', 'T161', 'T162', 'T163', 'T164', 'T165', 'T166', 'T167', 'T168', 'T169', 'T170', 'T171', 'T172', 'T173', 'T174', 'T175', 'T176', 'T177', 'T178', 'T179', 'T180', 'T181', 'T182', 'T183', 'T184', 'T185', 'T186', 'T187', 'T188', 'T189', 'T190', 'T191', 'T192', 'T193', 'T194', 'T195', 'T196', 'T197', 'T198', 'T199', 'T200']],
            ['brand' => 'LYNK&CO', 'model' => ['01', '02', '03', '04', '05']],
            ['brand' => 'MAHINDRA', 'model' => ['Bolero', 'Scorpio', 'Thar', 'XUV500', 'Xylo']],
            ['brand' => 'MAN', 'model' => ['TGL', 'TGM', 'TGS', 'TGX']],
            ['brand' => 'MARUTI', 'model' => ['800', 'Alto', 'Baleno', 'Celerio', 'Ciaz', 'Dzire', 'Eeco', 'Ertiga', 'Esteem', 'Gypsy', 'Ignis', 'Omni', 'Ritz', 'S-Cross', 'S-Presso', 'Swift', 'SX4', 'Versa', 'Vitara Brezza', 'Wagon R', 'XL6']],
            ['brand' => 'MASERATI', 'model' => ['228', '3200 GT', '420', '430', 'Barchetta', 'Biturbo', 'Chubasco', 'Ghibli', 'GranCabrio', 'GranSport', 'GranTurismo', 'Indy', 'Karif', 'Khamsin', 'Kyalami', 'Levante', 'MC12', 'Merak', 'Mexico', 'Quattroporte', 'Royale', 'Shamal', 'Spyder']],
            ['brand' => 'MATRA', 'model' => ['530', 'Bagheera', 'Djet', 'Murena', 'Rancho']],
            ['brand' => 'MAZDA', 'model' => ['121', '2', '3', '323', '5', '6', '616', '626', '818', '929', 'Atenza', 'Axela', 'AZ-1', 'B-Series', 'Biante', 'Bongo', 'BT-50', 'Carol', 'CX-3', 'CX-30', 'CX-4', 'CX-5', 'CX-7', 'CX-8', 'CX-9', 'Demio', 'E-Series', 'Efini MS-6', 'Eunos', 'Familia', 'Lantis', 'MPV', 'MX-3', 'MX-30', 'MX-5', 'MX-6', 'Navajo', 'Premacy', 'Proceed', 'Protege', 'Revolution', 'Roadster', 'RX-2', 'RX-3', 'RX-4', 'RX-7', 'RX-8', 'Savanna', 'Scrum', 'Sentia', 'Spiano', 'Tribute', 'Verisa']],
            ['brand' => 'MCC', 'model' => ['Smart']],
            ['brand' => 'MEGA', 'model' => ['Club', 'Monte Carlo']],
            ['brand' => 'MERCEDES', 'model' => ['190', '200', '220', '230', '240', '250', '260', '270', '280', '300', '350', '380', '400', '420', '450', '500', '560', '600', 'A-Class', 'AMG GT', 'B-Class', 'C-Class', 'CE-Class', 'CL-Class', 'CLA-Class', 'CLC-Class', 'CLK-Class', 'CLS-Class', 'E-Class', 'G-Class', 'GL-Class', 'GLA-Class', 'GLB-Class', 'GLC-Class', 'GLK-Class', 'GLS-Class', 'M-Class', 'Maybach', 'R-Class', 'S-Class', 'SL-Class', 'SLC-Class', 'SLK-Class', 'SLR McLaren', 'SLS AMG', 'Vaneo', 'V-Class', 'Viano', 'W123', 'W124', 'W140', 'W201']],
            ['brand' => 'MG', 'model' => ['1100', '1300', 'F', 'Maestro', 'MGB', 'MGC', 'Midget', 'RV8', 'TD', 'TF', 'ZS', 'ZT', 'ZR', 'ZS', 'ZT', 'ZT-T']],
            ['brand' => 'MIA', 'model' => ['1', 'LW']],
            ['brand' => 'MINI', 'model' => ['Clubman', 'Cabriolet', 'Countryman', 'Coupe', 'E', 'John Cooper Works', 'One', 'Paceman', 'Roadster']],
            ['brand' => 'MITSUBISHI', 'model' => ['3000GT', '380', 'ASX', 'Carisma', 'Celeste', 'Challenger', 'Chariot', 'Colt', 'Cordia', 'Delica', 'Diamante', 'Dingo', 'Eclipse', 'eK', 'Endeavor', 'FTO', 'Galant', 'Grandis', 'GTO', 'L200', 'L300', 'L400', 'Lancer', 'Lancer Evolution', 'Magna', 'Maven', 'Mirage', 'Montero', 'Outlander', 'Pajero', 'Precis', 'RVR', 'Santamo', 'Sapporo', 'Shogun', 'Shogun Sport', 'Sigma', 'Space Gear', 'Space Runner', 'Space Star', 'Space Wagon', 'Starion', 'Tredia', 'Triton']],
            ['brand' => 'MPM MOTORS', 'model' => ['Erelis', 'PS']],
            ['brand' => 'NISSAN', 'model' => ['100NX', '180SX', '200SX', '280ZX', '300ZX', '350Z', '370Z', 'Almera', 'Altima', 'Armada', 'Bluebird', 'Cedric', 'Cherry', 'Cima', 'Crew', 'Cube', 'Datsun', 'Elgrand', 'Fairlady Z', 'Figaro', 'Frontier', 'Gloria', 'GT-R', 'Hardbody', 'Juke', 'Kicks', 'Kix', 'Lafesta', 'Largo', 'Laurel', 'Leaf', 'Leopard', 'Livina', 'Maxima', 'Micra', 'Moco', 'Murano', 'Navara', 'Note', 'NP300', 'NV', 'NX', 'Otti', 'Pathfinder', 'Patrol', 'PickUp', 'Pixo', 'Prairie', 'Presage', 'Pulsar', 'Qashqai', 'Quest', 'Rasheen', 'Rogue', 'Safari', 'Sentra', 'Serena', 'Silvia', 'Skyline', 'Stanza', 'Sunny', 'Teana', 'Terrano', 'Tiida', 'Titan', 'Vanette', 'Versa', 'Wingroad', 'X-Trail', 'Xterra']],
            ['brand' => 'OPEL', 'model' => ['Adam', 'Agila', 'Ampera', 'Antara', 'Ascona', 'Astra', 'Calibra', 'Campo', 'Cascada', 'Combo', 'Commodore', 'Corsa', 'Crossland X', 'Frontera', 'Grandland X', 'GT', 'Insignia', 'Kadett', 'Karl', 'Manta', 'Meriva', 'Mokka', 'Monterey', 'Monza', 'Movano', 'Olympia', 'Omega', 'Rekord', 'Senator', 'Signum', 'Sintra', 'Speedster', 'Tigra', 'Vectra', 'Vivaro', 'Zafira']],
            ['brand' => 'PANHARD', 'model' => ['16', '24', '35', '50', 'Dynavia', 'Dyna X', 'Dyna Z', 'Levassor', 'Panhard', 'PL 17', 'Tigre', 'Z']],
            ['brand' => 'PEUGEOT', 'model' => ['1007', '104', '106', '107', '108', '2008', '204', '205', '206', '207', '208', '3008', '301', '304', '305', '306', '307', '308', '309', '4007', '4008', '404', '405', '406', '407', '408', '5008', '504', '505', '508', '604', '605', '607', '806', '807', 'Bipper', 'Boxer', 'Expert', 'iOn', 'Partner', 'RCZ', 'Rifter', 'Traveller']],
            ['brand' => 'PIAGGIO', 'model' => ['Porter', 'Quargo']],
            ['brand' => 'PONTIAC', 'model' => ['6000', 'Aztek', 'Bonneville', 'Catalina', 'Fiero', 'Firebird', 'G3', 'G4', 'G5', 'G6', 'G8', 'Grand Am', 'Grand Prix', 'GTO', 'LeMans', 'Montana', 'Phoenix', 'Solstice', 'Sunbird', 'Sunfire', 'T1000', 'Tempest', 'Torrent', 'Trans Sport', 'Vibe']],
            ['brand' => 'PORSCHE', 'model' => ['356', '550', '718', '911', '912', '914', '918', '924', '928', '930', '944', '959', '964', '968', 'Boxster', 'Carrera GT', 'Cayenne', 'Cayman', 'Macan', 'Panamera', 'Taycan']],
            ['brand' => 'PROTON', 'model' => ['Arena', 'EMAS', 'Ertiga', 'Gen-2', 'Inspira', 'Iriz', 'Jumbuck', 'Perdana', 'Persona', 'Preve', 'Putra', 'Saga', 'Satria', 'Savvy', 'Suprima S', 'Waja', 'Wira']],
            ['brand' => 'RENAULT', 'model' => ['Alaskan', 'Arkana', 'Avantime', 'Captur', 'Clio', 'Dokker', 'Duster', 'Espace', 'Floride', 'Fuego', 'Grand Espace', 'Grand Modus', 'Grand Scénic', 'Kadjar', 'Kangoo', 'Kaptur', 'Koleos', 'KWID', 'Laguna', 'Latitude', 'Lodgy', 'Logan', 'Master', 'Maxity', 'Mégane', 'Modus', 'Primer', 'Pulse', 'Rapid', 'Rodeo', 'Safrane', 'Samsung SM3', 'Samsung SM5', 'Samsung SM7', 'Sandero', 'Savanna', 'Scénic', 'Sport Spider', 'Supercinq', 'Symbol', 'Talisman', 'Thalia', 'Trafic', 'Twingo', 'Twizy', 'Vel Satis', 'Wind', 'ZOE']],
            ['brand' => 'ROVER', 'model' => ['100', '200', '25', '400', '45', '600', '75', '800', 'CityRover', 'Metro', 'Mini', 'Montego', 'SD1', 'Streetwise']],
            ['brand' => 'SAAB', 'model' => ['9-2X', '9-3', '9-4X', '9-5', '9-7X', '90', '900', '9000', '92', '93', '95', '96', '99']],
            ['brand' => 'SANTANA', 'model' => ['300', 'Aníbal', 'Ligero', 'PS-10']],
            ['brand' => 'SEAT', 'model' => ['124', '127', '131', '132', '133', '1400', '1430', '1500', '600', '850', 'Alhambra', 'Altea', 'Arona', 'Arosa', 'Ateca', 'Córdoba', 'Exeo', 'Fura', 'Ibiza', 'Inca', 'León', 'Malaga', 'Marbella', 'Mii', 'Panda', 'Ritmo', 'Tarraco', 'Toledo']],
            ['brand' => 'SKODA', 'model' => ['1000 MB', '105', '120', '130', 'Citigo', 'Enyaq', 'Fabia', 'Favorit', 'Felicia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Popular', 'Rapid', 'Roomster', 'Scala', 'Superb', 'Yeti']],
            ['brand' => 'SMART', 'model' => ['Crossblade', 'EQ', 'Forfour', 'Fortwo', 'Roadster']],
            ['brand' => 'SSANGYONG', 'model' => ['Actyon', 'Chairman', 'Istana', 'Korando', 'Kyron', 'Musso', 'Nomad', 'Rexton', 'Rodius', 'Stavic', 'Tivoli', 'XLV']],
            ['brand' => 'SUBARU', 'model' => ['Baja', 'BRZ', 'Domingo', 'Forester', 'Impreza', 'Justy', 'Leone', 'Levorg', 'Libero', 'Outback', 'Pleo', 'Rex', 'SVX', 'Tribeca', 'Vivio', 'WRX', 'XT', 'XV']],
            ['brand' => 'SUZUKI', 'model' => ['Aerio', 'Alto', 'Baleno', 'Cappuccino', 'Carry', 'Celerio', 'Cervo', 'Cultus', 'Ertiga', 'Escudo', 'Every', 'Forenza', 'Grand Vitara', 'Ignis', 'Jimny', 'Kei', 'Kizashi', 'Landy', 'Liana', 'LJ', 'MR Wagon', 'Palette', 'R', 'Samurai', 'Sidekick', 'Solio', 'Splash', 'Swift', 'SX4', 'SX4 S-Cross', 'SX4 Sportback', 'Verona', 'Vitara', 'Wagon R', 'X-90', 'XL7']],
            ['brand' => 'TALBOT', 'model' => ['1100', '1307', '1510', '90', 'Avenger', 'Horizon', 'Matra-Simca Bagheera', 'Matra-Simca Rancho', 'Rancho', 'Samba', 'Solara', 'Sunbeam', 'Tagora']],
            ['brand' => 'TATA', 'model' => ['Ace', 'Aria', 'Bolt', 'Estate', 'Harrier', 'Indica', 'Indigo', 'Manza', 'Nano', 'Nexon', 'Safari', 'Sierra', 'Sumo', 'Tiago', 'Tigor', 'Winger', 'Xenon', 'Yodha', 'Zest']],
            ['brand' => 'TESLA', 'model' => ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster']],
            ['brand' => 'TOYOTA', 'model' => ['4Runner', '86', 'Aurion', 'Avalon', 'Avanza', 'Avensis', 'Aygo', 'bB', 'Belta', 'Blade', 'C-HR', 'Camry', 'Carina', 'Celica', 'Century', 'Coaster', 'Comfort', 'Corolla', 'Crown', 'Curren', 'Cynos', 'Duet', 'Echo', 'Esquire', 'Estima', 'Etios', 'FJ Cruiser', 'Fortuner', 'Granvia', 'GT86', 'Harrier', 'Hiace', 'Highlander', 'Hilux', 'Innova', 'Ipsum', 'IQ', 'ist', 'Kluger', 'Land Cruiser', 'LiteAce', 'Mark II', 'Matrix', 'Mirai', 'MR2', 'Passo', 'Picnic', 'Platz', 'Porte', 'Previa', 'Prius', 'Probox', 'Progres', 'Ractis', 'Raum', 'Rav4', 'RegiusAce', 'Roomy', 'Rush', 'Sai', 'Scepter', 'Sequoia', 'Sienna', 'Sienta', 'Soarer', 'Succeed', 'Supra', 'Tacoma', 'Tercel', 'TownAce', 'Tundra', 'Urban Cruiser', 'Vanguard', 'Vellfire', 'Venza', 'Verso', 'Vios', 'Vista', 'Vitz', 'Voxy', 'Wish', 'Yaris']],
            ['brand' => 'VOLKSWAGEN', 'model' => ['181', 'Amarok', 'Arteon', 'Beetle', 'Bora', 'Buggy', 'Caddy', 'Caravelle', 'CC', 'Corrado', 'Crafter', 'Derby', 'Eos', 'Fox', 'Golf', 'I.D.', 'ID.3', 'ID.4', 'Jetta', 'Karmann Ghia', 'Lavida', 'LT', 'Lupo', 'Multivan', 'Parati', 'Passat', 'Phaeton', 'Pointer', 'Polo', 'Rabbit', 'Routan', 'Santana', 'Saveiro', 'Scirocco', 'Sharan', 'T-Cross', 'T-Roc', 'Taro', 'Tiguan', 'Touareg', 'Touran', 'Transporter', 'Up!', 'Vento']],
            ['brand' => 'VOLVO', 'model' => ['120', '140', '144', '145', '164', '240', '242', '244', '245', '260', '264', '265', '340', '360', '440', '460', '480', '66', '740', '760', '780', '850', '940', '960', 'C30', 'C70', 'P120', 'P1800', 'P1900', 'P220', 'P544', 'P445', 'S40', 'S60', 'S70', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'XC40', 'XC60', 'XC70', 'XC90']],
        ];
    }
}
